import { Hono } from "hono";
import type { AppEnv } from "../types";
import { AppError } from "../lib/errors";
import { readJsonObject } from "../lib/json";
import { requireAuth } from "../middleware/auth";

function ids(first:string,second:string){return [first,second].sort() as [string,string];}

export const globalRelationshipRoutes=new Hono<AppEnv>();
globalRelationshipRoutes.use("*",requireAuth);

globalRelationshipRoutes.get("/me/connections",async(c)=>{const auth=c.get("auth");const user=await c.env.DB.prepare(`SELECT public_handle,discoverability FROM platform_users WHERE id=?`).bind(auth.userId).first<any>();const rows=await c.env.DB.prepare(`SELECT connections.*,CASE WHEN connections.user_low_id=? THEN high.display_name ELSE low.display_name END AS display_name,CASE WHEN connections.user_low_id=? THEN high.public_handle ELSE low.public_handle END AS public_handle FROM user_connections connections JOIN platform_users low ON low.id=connections.user_low_id JOIN platform_users high ON high.id=connections.user_high_id WHERE connections.user_low_id=? OR connections.user_high_id=? ORDER BY connections.updated_at DESC`).bind(auth.userId,auth.userId,auth.userId,auth.userId).all<any>();const notices=await c.env.DB.prepare(`SELECT * FROM global_notifications WHERE recipient_user_id=? AND acted_at IS NULL ORDER BY created_at DESC`).bind(auth.userId).all();return c.json({ok:true,profile:{publicHandle:user?.public_handle||"",discoverability:user?.discoverability||"private"},connections:(rows.results||[]).map((row)=>({userId:row.user_low_id===auth.userId?row.user_high_id:row.user_low_id,displayName:row.display_name,publicHandle:row.public_handle,status:row.status,requestedByMe:row.requested_by_user_id===auth.userId})),notifications:notices.results||[]});});

globalRelationshipRoutes.put("/me/discoverability",async(c)=>{const auth=c.get("auth");const body=await readJsonObject(c);const mode=["private","exact-handle","invite-only"].includes(String(body.discoverability))?String(body.discoverability):"private";const handle=typeof body.publicHandle==="string"?body.publicHandle.trim().toLowerCase():"";if(mode==="exact-handle"&&!/^[a-z0-9][a-z0-9._-]{2,31}$/.test(handle))throw new AppError(400,"invalid_handle","Public handle must contain 3-32 safe characters.");try{await c.env.DB.prepare(`UPDATE platform_users SET public_handle=?,discoverability=?,updated_at=? WHERE id=?`).bind(handle||null,mode,new Date().toISOString(),auth.userId).run();}catch(error){if(/UNIQUE/i.test(String(error)))throw new AppError(409,"handle_taken","This handle is already used.");throw error;}return c.json({ok:true,profile:{publicHandle:handle,discoverability:mode}});});

globalRelationshipRoutes.post("/connections",async(c)=>{const auth=c.get("auth");const body=await readJsonObject(c);const handle=typeof body.publicHandle==="string"?body.publicHandle.trim().toLowerCase():"";const target=await c.env.DB.prepare(`SELECT id,display_name FROM platform_users WHERE public_handle=? COLLATE NOCASE AND discoverability='exact-handle' AND status='active'`).bind(handle).first<any>();if(!target||target.id===auth.userId)throw new AppError(404,"user_not_found","No opted-in player has this exact handle.");const [low,high]=ids(auth.userId,target.id);const existing=await c.env.DB.prepare(`SELECT status FROM user_connections WHERE user_low_id=? AND user_high_id=?`).bind(low,high).first<any>();if(existing&&["pending","accepted","blocked"].includes(existing.status))throw new AppError(409,"connection_exists","A connection or request already exists.");const now=new Date().toISOString();await c.env.DB.batch([c.env.DB.prepare(`INSERT INTO user_connections (user_low_id,user_high_id,requested_by_user_id,status,created_at,updated_at) VALUES (?,?,?,'pending',?,?) ON CONFLICT(user_low_id,user_high_id) DO UPDATE SET requested_by_user_id=excluded.requested_by_user_id,status='pending',updated_at=excluded.updated_at`).bind(low,high,auth.userId,now,now),c.env.DB.prepare(`INSERT INTO global_notifications (id,recipient_user_id,actor_user_id,type,title,body,entity_type,entity_id,created_at) VALUES (?,?,?,'connection_request','Nova meziklubova zadost','Hrac vas chce propojit bez sdileni klubovych seznamu.','connection',?,?)`).bind(crypto.randomUUID(),target.id,auth.userId,`${low}:${high}`,now)]);return c.json({ok:true},201);});

globalRelationshipRoutes.post("/connections/:otherUserId/respond",async(c)=>{const auth=c.get("auth");const body=await readJsonObject(c);const response=body.response==="accept"?"accepted":body.response==="decline"?"declined":null;if(!response)throw new AppError(400,"invalid_response","Response must be accept or decline.");const other=c.req.param("otherUserId");const [low,high]=ids(auth.userId,other);const connection=await c.env.DB.prepare(`SELECT requested_by_user_id,status FROM user_connections WHERE user_low_id=? AND user_high_id=?`).bind(low,high).first<any>();if(!connection||connection.status!=="pending"||connection.requested_by_user_id===auth.userId)throw new AppError(409,"request_not_pending","No incoming request is pending.");const now=new Date().toISOString();await c.env.DB.batch([c.env.DB.prepare(`UPDATE user_connections SET status=?,updated_at=? WHERE user_low_id=? AND user_high_id=?`).bind(response,now,low,high),c.env.DB.prepare(`UPDATE global_notifications SET acted_at=?,read_at=COALESCE(read_at,?) WHERE recipient_user_id=? AND entity_type='connection' AND entity_id=? AND acted_at IS NULL`).bind(now,now,auth.userId,`${low}:${high}`)]);return c.json({ok:true,status:response});});
