import { Hono } from "hono";
import type { AppEnv } from "../types";
import { requireClubMembership } from "../clubs/access";
import { AppError } from "../lib/errors";
import { requireAuth } from "../middleware/auth";

const allowedTypes=new Set(["image/jpeg","image/png","image/webp"]);
const maxBytes=8*1024*1024;

export const mediaRoutes=new Hono<AppEnv>();
mediaRoutes.use("*",requireAuth);

mediaRoutes.post("/media",async(c)=>{const auth=c.get("auth");if(!c.env.MEDIA)throw new AppError(503,"media_unavailable","Media storage is not configured in this environment.");const clubId=c.req.query("clubId")||"";if(clubId)await requireClubMembership(c.env.DB,auth.userId,clubId);const type=(c.req.header("Content-Type")||"").split(";",1)[0]!.toLowerCase();if(!allowedTypes.has(type))throw new AppError(415,"unsupported_media","Only JPEG, PNG and WebP images are supported.");const bytes=await c.req.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>maxBytes)throw new AppError(413,"media_too_large","Image must be between 1 byte and 8 MB.");const entityType=(c.req.query("entityType")||"profile").slice(0,40);const entityId=(c.req.query("entityId")||"").slice(0,80)||null;const ext=type==="image/jpeg"?"jpg":type.split("/")[1];const id=crypto.randomUUID();const key=`${clubId||"users"}/${auth.userId}/${id}.${ext}`;await c.env.MEDIA.put(key,bytes,{httpMetadata:{contentType:type,cacheControl:"private, max-age=3600"},customMetadata:{ownerUserId:auth.userId,clubId,entityType,entityId:entityId||""}});await c.env.DB.prepare(`INSERT INTO media_assets (id,club_id,owner_user_id,entity_type,entity_id,object_key,mime_type,byte_size,status,created_at) VALUES (?,?,?,?,?,?,?,?,'active',?)`).bind(id,clubId||null,auth.userId,entityType,entityId,key,type,bytes.byteLength,new Date().toISOString()).run();return c.json({ok:true,asset:{id,url:`/api/v2/media/${id}`,mimeType:type,byteSize:bytes.byteLength}},201);});

mediaRoutes.get("/media/:assetId",async(c)=>{const auth=c.get("auth");if(!c.env.MEDIA)throw new AppError(503,"media_unavailable","Media storage is not configured in this environment.");const asset=await c.env.DB.prepare(`SELECT * FROM media_assets WHERE id=? AND status='active'`).bind(c.req.param("assetId")).first<any>();if(!asset)throw new AppError(404,"media_not_found","Media does not exist.");if(asset.owner_user_id!==auth.userId){if(!asset.club_id)throw new AppError(403,"forbidden","This media is private.");await requireClubMembership(c.env.DB,auth.userId,asset.club_id);}const object=await c.env.MEDIA.get(asset.object_key);if(!object)throw new AppError(404,"media_not_found","Media object is missing.");const headers=new Headers();object.writeHttpMetadata(headers);headers.set("ETag",object.httpEtag);headers.set("Cache-Control","private, max-age=3600");return new Response(object.body,{headers});});

mediaRoutes.delete("/media/:assetId",async(c)=>{const auth=c.get("auth");if(!c.env.MEDIA)throw new AppError(503,"media_unavailable","Media storage is not configured in this environment.");const asset=await c.env.DB.prepare(`SELECT * FROM media_assets WHERE id=? AND status='active'`).bind(c.req.param("assetId")).first<any>();if(!asset)throw new AppError(404,"media_not_found","Media does not exist.");let allowed=asset.owner_user_id===auth.userId;if(!allowed&&asset.club_id){const membership=await requireClubMembership(c.env.DB,auth.userId,asset.club_id);allowed=["admin","manager"].includes(membership.role);}if(!allowed)throw new AppError(403,"forbidden","You cannot delete this media.");await c.env.MEDIA.delete(asset.object_key);await c.env.DB.prepare(`UPDATE media_assets SET status='deleted',deleted_at=? WHERE id=?`).bind(new Date().toISOString(),asset.id).run();return c.json({ok:true});});
