import { Hono } from "hono";
import type { AppEnv } from "../types";
import { requireClubMembership } from "../clubs/access";
import { AppError } from "../lib/errors";
import { readJsonObject } from "../lib/json";
import { requireAuth } from "../middleware/auth";

const datePattern = /^\d{4}-\d{2}-\d{2}$/;

function dayKeys(date: string) {
  const day = new Date(`${date}T12:00:00Z`).getUTCDay();
  return [`date:${date}`, day === 0 || day === 6 ? "weekend" : "weekdays", "all"];
}

async function reservationPrice(db: D1Database, clubId: string, reservationId: string) {
  const reservation = await db.prepare(`SELECT r.*,COALESCE(p.base_discount_pct,0)+COALESCE(p.loyalty_discount_pct,0) AS discount_pct FROM reservations r LEFT JOIN member_club_profiles p ON p.membership_id=r.owner_membership_id WHERE r.id=? AND r.club_id=?`).bind(reservationId,clubId).first<any>();
  if(!reservation) throw new AppError(404,"reservation_not_found","Reservation does not exist.");
  const rules=await db.prepare(`SELECT day_key,start_time,end_time,price_minor FROM court_price_rules WHERE club_id=? AND court_id=? AND day_key IN (?,?,?) ORDER BY CASE day_key WHEN ? THEN 0 WHEN 'weekdays' THEN 1 WHEN 'weekend' THEN 1 ELSE 2 END`).bind(clubId,reservation.court_id,...dayKeys(reservation.reservation_date),`date:${reservation.reservation_date}`).all<any>();
  const start=Number(reservation.start_time.slice(0,2))*60+Number(reservation.start_time.slice(3)); const end=Number(reservation.end_time.slice(0,2))*60+Number(reservation.end_time.slice(3)); let gross=0;
  for(let minute=start;minute<end;minute+=30){const time=`${String(Math.floor(minute/60)).padStart(2,"0")}:${String(minute%60).padStart(2,"0")}`; const rule=(rules.results||[]).find((item)=>item.start_time<=time&&item.end_time>time); gross+=Math.round(Number(rule?.price_minor||0)/2);}
  const discount=Math.min(80,Math.max(0,Number(reservation.discount_pct||0))); return {reservation,gross,discount,final:Math.round(gross*(100-discount)/100)};
}

export const operationRoutes = new Hono<AppEnv>();
operationRoutes.use("*", requireAuth);

operationRoutes.get("/clubs/:clubId/me/charges", async (c) => {
  const auth=c.get("auth"); const clubId=c.req.param("clubId"); const member=await requireClubMembership(c.env.DB,auth.userId,clubId);
  const rows=await c.env.DB.prepare(`SELECT charges.*,r.reservation_date,r.start_time,r.end_time,courts.name AS court_name FROM reservation_charges charges JOIN reservations r ON r.id=charges.reservation_id JOIN club_courts courts ON courts.id=r.court_id WHERE charges.club_id=? AND charges.membership_id=? ORDER BY r.reservation_date DESC,r.start_time DESC`).bind(clubId,member.membershipId).all();
  return c.json({ok:true,charges:rows.results||[]});
});

operationRoutes.get("/clubs/:clubId/charges", async (c) => {
  const auth=c.get("auth"); const clubId=c.req.param("clubId"); await requireClubMembership(c.env.DB,auth.userId,clubId,["admin","manager"]);
  const rows=await c.env.DB.prepare(`SELECT charges.*,r.reservation_date,r.start_time,r.end_time,courts.name AS court_name,COALESCE(m.display_name_override,u.display_name) AS player FROM reservation_charges charges JOIN reservations r ON r.id=charges.reservation_id JOIN club_courts courts ON courts.id=r.court_id JOIN club_memberships m ON m.id=charges.membership_id JOIN platform_users u ON u.id=m.user_id WHERE charges.club_id=? ORDER BY r.reservation_date DESC,r.start_time DESC`).bind(clubId).all();
  return c.json({ok:true,charges:rows.results||[]});
});

operationRoutes.get("/clubs/:clubId/charges/export.csv", async (c) => {
  const auth=c.get("auth"); const clubId=c.req.param("clubId"); await requireClubMembership(c.env.DB,auth.userId,clubId,["admin","manager"]);
  const rows=await c.env.DB.prepare(`SELECT r.reservation_date,r.start_time,r.end_time,courts.name AS court_name,COALESCE(m.display_name_override,u.display_name) AS player,charges.gross_minor,charges.discount_pct,charges.final_minor,charges.payment_method,charges.status,charges.settled_at FROM reservation_charges charges JOIN reservations r ON r.id=charges.reservation_id JOIN club_courts courts ON courts.id=r.court_id JOIN club_memberships m ON m.id=charges.membership_id JOIN platform_users u ON u.id=m.user_id WHERE charges.club_id=? ORDER BY r.reservation_date DESC,r.start_time DESC`).bind(clubId).all<Record<string,unknown>>();
  const escape=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
  const header=["datum","od","do","kurt","hrac","cena_pred_slevou_minor","sleva_pct","finalni_cena_minor","platba","stav","zuctovano"];
  const csv=[header.map(escape).join(";"),...(rows.results||[]).map((row)=>[row.reservation_date,row.start_time,row.end_time,row.court_name,row.player,row.gross_minor,row.discount_pct,row.final_minor,row.payment_method,row.status,row.settled_at].map(escape).join(";"))].join("\r\n");
  c.header("Content-Type","text/csv; charset=utf-8"); c.header("Content-Disposition",`attachment; filename="${clubId}-platby.csv"`); return c.body(`\uFEFF${csv}`);
});

operationRoutes.post("/clubs/:clubId/reservations/:reservationId/settle", async (c) => {
  const auth=c.get("auth"); const clubId=c.req.param("clubId"); const actor=await requireClubMembership(c.env.DB,auth.userId,clubId); const priced=await reservationPrice(c.env.DB,clubId,c.req.param("reservationId"));
  if(actor.membershipId!==priced.reservation.owner_membership_id&&!['admin','manager'].includes(actor.role)) throw new AppError(403,"forbidden","Only the reservation owner or club staff can settle this reservation.");
  const existing=await c.env.DB.prepare(`SELECT id,status FROM reservation_charges WHERE club_id=? AND reservation_id=?`).bind(clubId,priced.reservation.id).first<any>(); if(existing) return c.json({ok:true,charge:existing,idempotent:true});
  const body=await readJsonObject(c); const method=typeof body.paymentMethod==="string"&&["credit","cash","bank","qr","card","other"].includes(body.paymentMethod)?body.paymentMethod:"credit"; const account=await c.env.DB.prepare(`SELECT paid_balance_minor,bonus_balance_minor FROM member_credit_accounts WHERE membership_id=? AND club_id=?`).bind(priced.reservation.owner_membership_id,clubId).first<any>();
  let remaining=priced.final; let bonus=0; let paid=0; let external=0; if(method==="credit"){bonus=Math.min(remaining,Number(account?.bonus_balance_minor||0));remaining-=bonus;paid=Math.min(remaining,Number(account?.paid_balance_minor||0));remaining-=paid;if(remaining>0) throw new AppError(409,"insufficient_credit","Player credit is insufficient.");}else external=remaining;
  const now=new Date().toISOString(); const id=crypto.randomUUID(); const statements:D1PreparedStatement[]=[];
  if(method==="credit") statements.push(c.env.DB.prepare(`UPDATE member_credit_accounts SET paid_balance_minor=paid_balance_minor-?,bonus_balance_minor=bonus_balance_minor-?,updated_at=? WHERE membership_id=? AND club_id=?`).bind(paid,bonus,now,priced.reservation.owner_membership_id,clubId));
  statements.push(c.env.DB.prepare(`INSERT INTO reservation_charges (id,club_id,reservation_id,membership_id,gross_minor,discount_pct,final_minor,paid_credit_minor,bonus_credit_minor,external_paid_minor,status,payment_method,settled_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,'paid',?,?,?,?)`).bind(id,clubId,priced.reservation.id,priced.reservation.owner_membership_id,priced.gross,priced.discount,priced.final,paid,bonus,external,method,now,now,now));
  if(method==="credit") statements.push(c.env.DB.prepare(`INSERT INTO credit_transactions (id,club_id,membership_id,transaction_type,paid_delta_minor,bonus_delta_minor,paid_balance_after_minor,bonus_balance_after_minor,payment_method,note,idempotency_key,actor_user_id,created_at) SELECT ?,?,?,'charge',?,?,paid_balance_minor,bonus_balance_minor,'other',?,?,?,? FROM member_credit_accounts WHERE membership_id=?`).bind(crypto.randomUUID(),clubId,priced.reservation.owner_membership_id,-paid,-bonus,`Kurt ${priced.reservation.reservation_date} ${priced.reservation.start_time}`,`reservation:${priced.reservation.id}`,auth.userId,now,priced.reservation.owner_membership_id));
  await c.env.DB.batch(statements); return c.json({ok:true,charge:{id,grossMinor:priced.gross,discountPct:priced.discount,finalMinor:priced.final,paidCreditMinor:paid,bonusCreditMinor:bonus,externalPaidMinor:external,status:"paid"}},201);
});

operationRoutes.post("/clubs/:clubId/charges/:chargeId/refund", async (c) => {
  const auth=c.get("auth"); const clubId=c.req.param("clubId"); await requireClubMembership(c.env.DB,auth.userId,clubId,["admin"]); const charge=await c.env.DB.prepare(`SELECT * FROM reservation_charges WHERE id=? AND club_id=? AND status='paid'`).bind(c.req.param("chargeId"),clubId).first<any>(); if(!charge) throw new AppError(409,"charge_not_refundable","Paid charge does not exist or was already refunded."); const now=new Date().toISOString(); const statements:D1PreparedStatement[]=[c.env.DB.prepare(`UPDATE reservation_charges SET status='refunded',refunded_at=?,updated_at=? WHERE id=?`).bind(now,now,charge.id)];
  if(Number(charge.paid_credit_minor)+Number(charge.bonus_credit_minor)>0){statements.push(c.env.DB.prepare(`UPDATE member_credit_accounts SET paid_balance_minor=paid_balance_minor+?,bonus_balance_minor=bonus_balance_minor+?,updated_at=? WHERE membership_id=?`).bind(charge.paid_credit_minor,charge.bonus_credit_minor,now,charge.membership_id));statements.push(c.env.DB.prepare(`INSERT INTO credit_transactions (id,club_id,membership_id,transaction_type,paid_delta_minor,bonus_delta_minor,paid_balance_after_minor,bonus_balance_after_minor,payment_method,note,idempotency_key,actor_user_id,created_at) SELECT ?,?,?,'refund',?,?,paid_balance_minor,bonus_balance_minor,'other',?,?,?,? FROM member_credit_accounts WHERE membership_id=?`).bind(crypto.randomUUID(),clubId,charge.membership_id,charge.paid_credit_minor,charge.bonus_credit_minor,"Vraceni platby za kurt",`refund:${charge.id}`,auth.userId,now,charge.membership_id));}
  await c.env.DB.batch(statements); return c.json({ok:true});
});

operationRoutes.get("/clubs/:clubId/analytics", async (c) => {
  const auth=c.get("auth"); const clubId=c.req.param("clubId"); await requireClubMembership(c.env.DB,auth.userId,clubId,["admin","manager"]); const from=datePattern.test(c.req.query("from")||"")?c.req.query("from")!:new Date(Date.now()-90*86400000).toISOString().slice(0,10); const to=datePattern.test(c.req.query("to")||"")?c.req.query("to")!:new Date().toISOString().slice(0,10);
  const [courts,months,total]=await Promise.all([
    c.env.DB.prepare(`SELECT courts.id,courts.name,(SELECT COUNT(*) FROM reservation_slots slots JOIN reservations r ON r.id=slots.reservation_id WHERE r.court_id=courts.id AND r.reservation_date BETWEEN ? AND ? AND r.status IN ('confirmed','completed')) AS occupied_slots,CAST((julianday(?)-julianday(?)+1)*(((CAST(substr(courts.close_time,1,2) AS INTEGER)*60+CAST(substr(courts.close_time,4,2) AS INTEGER))-(CAST(substr(courts.open_time,1,2) AS INTEGER)*60+CAST(substr(courts.open_time,4,2) AS INTEGER)))/30) AS INTEGER) AS available_slots,(SELECT COALESCE(SUM(charges.final_minor),0) FROM reservation_charges charges JOIN reservations paid_reservation ON paid_reservation.id=charges.reservation_id WHERE paid_reservation.court_id=courts.id AND paid_reservation.reservation_date BETWEEN ? AND ? AND charges.status='paid') AS revenue_minor FROM club_courts courts WHERE courts.club_id=? ORDER BY courts.sort_order`).bind(from,to,to,from,from,to,clubId).all<any>(),
    c.env.DB.prepare(`SELECT substr(r.reservation_date,1,7) AS month,SUM(charges.final_minor) AS revenue_minor,COUNT(DISTINCT charges.id) AS paid_reservations FROM reservation_charges charges JOIN reservations r ON r.id=charges.reservation_id WHERE charges.club_id=? AND charges.status='paid' AND r.reservation_date BETWEEN ? AND ? GROUP BY month ORDER BY month`).bind(clubId,from,to).all<any>(),
    c.env.DB.prepare(`SELECT COALESCE(SUM(final_minor),0) AS revenue_minor,COUNT(*) AS paid_reservations FROM reservation_charges WHERE club_id=? AND status='paid'`).bind(clubId).first<any>(),
  ]);
  return c.json({ok:true,range:{from,to},summary:{revenueMinor:Number(total?.revenue_minor||0),paidReservations:Number(total?.paid_reservations||0)},courts:(courts.results||[]).map((row)=>({...row,occupied_slots:Number(row.occupied_slots||0),available_slots:Number(row.available_slots||0),occupancyPct:row.available_slots?Math.round(Number(row.occupied_slots)*100/Number(row.available_slots)):0,revenue_minor:Number(row.revenue_minor||0)})),months:months.results||[]});
});

operationRoutes.get("/me/privacy", async (c) => { const auth=c.get("auth"); const [preferences,consents,requests]=await Promise.all([c.env.DB.prepare(`SELECT * FROM privacy_preferences WHERE user_id=?`).bind(auth.userId).all(),c.env.DB.prepare(`SELECT * FROM privacy_consents WHERE user_id=? ORDER BY created_at DESC`).bind(auth.userId).all(),c.env.DB.prepare(`SELECT * FROM privacy_requests WHERE user_id=? ORDER BY requested_at DESC`).bind(auth.userId).all()]); return c.json({ok:true,policyVersion:"2026-08-01",preferences:preferences.results||[],consents:consents.results||[],requests:requests.results||[]}); });

operationRoutes.put("/me/privacy", async (c) => { const auth=c.get("auth"); const body=await readJsonObject(c); const purpose=typeof body.purpose==="string"?body.purpose.slice(0,80):""; const granted=body.granted===true?1:body.granted===false?0:null; const version=typeof body.policyVersion==="string"?body.policyVersion:"2026-08-01"; if(!purpose||granted===null) throw new AppError(400,"invalid_consent","Purpose and consent value are required."); const now=new Date().toISOString(); await c.env.DB.batch([c.env.DB.prepare(`INSERT INTO privacy_preferences (user_id,purpose,granted,policy_version,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(user_id,purpose) DO UPDATE SET granted=excluded.granted,policy_version=excluded.policy_version,updated_at=excluded.updated_at`).bind(auth.userId,purpose,granted,version,now),c.env.DB.prepare(`INSERT INTO privacy_consents (id,user_id,purpose,policy_version,granted,source,created_at) VALUES (?,?,?,?,?,'portal',?)`).bind(crypto.randomUUID(),auth.userId,purpose,version,granted,now)]); return c.json({ok:true}); });

operationRoutes.get("/me/export", async (c) => { const auth=c.get("auth"); const [user,memberships,reservations,orders,credits,connections]=await Promise.all([c.env.DB.prepare(`SELECT id,email,display_name,public_handle,avatar_url,status,discoverability,created_at,updated_at FROM platform_users WHERE id=?`).bind(auth.userId).first(),c.env.DB.prepare(`SELECT m.*,p.account_type,p.base_discount_pct,p.loyalty_discount_pct,p.discount_reason,p.admin_note FROM club_memberships m LEFT JOIN member_club_profiles p ON p.membership_id=m.id WHERE m.user_id=?`).bind(auth.userId).all(),c.env.DB.prepare(`SELECT r.* FROM reservations r JOIN reservation_participants p ON p.reservation_id=r.id JOIN club_memberships m ON m.id=p.membership_id WHERE m.user_id=?`).bind(auth.userId).all(),c.env.DB.prepare(`SELECT o.* FROM club_orders o JOIN club_memberships m ON m.id=o.membership_id WHERE m.user_id=?`).bind(auth.userId).all(),c.env.DB.prepare(`SELECT t.* FROM credit_transactions t JOIN club_memberships m ON m.id=t.membership_id WHERE m.user_id=?`).bind(auth.userId).all(),c.env.DB.prepare(`SELECT * FROM user_connections WHERE user_low_id=? OR user_high_id=?`).bind(auth.userId,auth.userId).all()]); return c.json({ok:true,exportedAt:new Date().toISOString(),user,memberships:memberships.results||[],reservations:reservations.results||[],orders:orders.results||[],creditTransactions:credits.results||[],connections:connections.results||[]}); });

operationRoutes.post("/me/privacy-requests", async (c) => { const auth=c.get("auth"); const body=await readJsonObject(c); const type=body.type==="erase"?"erase":body.type==="export"?"export":null; if(!type) throw new AppError(400,"invalid_request","Privacy request must be export or erase."); const existing=await c.env.DB.prepare(`SELECT id FROM privacy_requests WHERE user_id=? AND request_type=? AND status IN ('pending','processing')`).bind(auth.userId,type).first(); if(existing) throw new AppError(409,"request_pending","A request of this type is already pending."); const id=crypto.randomUUID(); await c.env.DB.prepare(`INSERT INTO privacy_requests (id,user_id,request_type,status,requested_at) VALUES (?,?,?,'pending',?)`).bind(id,auth.userId,type,new Date().toISOString()).run(); return c.json({ok:true,request:{id,type,status:"pending"}},201); });

operationRoutes.get("/me/notification-preferences", async (c) => { const auth=c.get("auth"); const row=await c.env.DB.prepare(`SELECT * FROM notification_preferences WHERE user_id=?`).bind(auth.userId).first(); return c.json({ok:true,preferences:row||{push_enabled:1,attendance_reminder_enabled:1,product_reminder_enabled:0,quiet_from:"22:00",quiet_to:"07:00"}}); });

operationRoutes.put("/me/notification-preferences", async (c) => { const auth=c.get("auth"); const body=await readJsonObject(c); const push=body.pushEnabled===false?0:1; const attendance=body.attendanceReminderEnabled===false?0:1; const product=body.productReminderEnabled===true?1:0; const quietFrom=typeof body.quietFrom==="string"?body.quietFrom:"22:00"; const quietTo=typeof body.quietTo==="string"?body.quietTo:"07:00"; const now=new Date().toISOString(); await c.env.DB.prepare(`INSERT INTO notification_preferences (user_id,push_enabled,attendance_reminder_enabled,product_reminder_enabled,quiet_from,quiet_to,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET push_enabled=excluded.push_enabled,attendance_reminder_enabled=excluded.attendance_reminder_enabled,product_reminder_enabled=excluded.product_reminder_enabled,quiet_from=excluded.quiet_from,quiet_to=excluded.quiet_to,updated_at=excluded.updated_at`).bind(auth.userId,push,attendance,product,quietFrom,quietTo,now).run(); return c.json({ok:true}); });

operationRoutes.get("/push/public-key", (c) => c.json({ok:true,publicKey:c.env.VAPID_PUBLIC_KEY||""}));
operationRoutes.post("/push/subscriptions", async (c) => { const auth=c.get("auth"); const body=await readJsonObject(c); const endpoint=typeof body.endpoint==="string"?body.endpoint:""; const keys=body.keys&&typeof body.keys==="object"?body.keys as Record<string,unknown>:{}; if(!endpoint.startsWith("https://")||typeof keys.p256dh!=="string"||typeof keys.auth!=="string") throw new AppError(400,"invalid_subscription","A valid Web Push subscription is required."); const now=new Date().toISOString(); await c.env.DB.prepare(`INSERT INTO push_subscriptions (id,user_id,endpoint,p256dh,auth,user_agent,enabled,failure_count,created_at,updated_at) VALUES (?,?,?,?,?,?,1,0,?,?) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,p256dh=excluded.p256dh,auth=excluded.auth,user_agent=excluded.user_agent,enabled=1,failure_count=0,updated_at=excluded.updated_at`).bind(crypto.randomUUID(),auth.userId,endpoint,keys.p256dh,keys.auth,c.req.header("User-Agent")||null,now,now).run(); return c.json({ok:true},201); });
operationRoutes.delete("/push/subscriptions", async (c) => { const auth=c.get("auth"); const body=await readJsonObject(c); await c.env.DB.prepare(`DELETE FROM push_subscriptions WHERE endpoint=? AND user_id=?`).bind(String(body.endpoint||""),auth.userId).run(); return c.json({ok:true}); });
