import { buildPushPayload } from "@block65/webcrypto-web-push";
import type { AppEnv } from "../types";

type Bindings=AppEnv["Bindings"];

async function createAttendanceReminders(env:Bindings,now:Date){const tomorrow=new Date(now);tomorrow.setUTCDate(tomorrow.getUTCDate()+1);const date=tomorrow.toISOString().slice(0,10);await env.DB.prepare(`INSERT INTO member_notifications (id,club_id,recipient_membership_id,type,title,body,entity_type,entity_id,created_at) SELECT lower(hex(randomblob(16))),r.club_id,p.membership_id,'attendance_reminder','Potvrdte zitrejsi hru',courts.name||', '||r.reservation_date||' '||r.start_time||'-'||r.end_time,'reservation_reminder',r.id,? FROM reservations r JOIN reservation_participants p ON p.reservation_id=r.id JOIN club_courts courts ON courts.id=r.court_id JOIN club_memberships memberships ON memberships.id=p.membership_id LEFT JOIN notification_preferences preferences ON preferences.user_id=memberships.user_id WHERE r.reservation_date=? AND r.status IN ('pending','confirmed','searching') AND p.status IN ('owner','confirmed','replacement') AND COALESCE(preferences.attendance_reminder_enabled,1)=1 AND NOT EXISTS (SELECT 1 FROM member_notifications existing WHERE existing.recipient_membership_id=p.membership_id AND existing.entity_type='reservation_reminder' AND existing.entity_id=r.id)`).bind(now.toISOString(),date).run();}

async function createStringingReminders(env:Bindings,now:Date){const cutoff=new Date(now);cutoff.setUTCDate(cutoff.getUTCDate()-30);await env.DB.prepare(`INSERT INTO member_notifications (id,club_id,recipient_membership_id,type,title,body,entity_type,entity_id,created_at) SELECT lower(hex(randomblob(16))),jobs.club_id,jobs.player_membership_id,'stringing_reminder','Neni cas na novy vyplet?','Od posledniho predani rakety uplynul mesic. Klub ji muze prevzit pred pristi hrou.','stringing_reminder',jobs.id,? FROM stringing_jobs jobs JOIN club_memberships memberships ON memberships.id=jobs.player_membership_id JOIN notification_preferences preferences ON preferences.user_id=memberships.user_id AND preferences.product_reminder_enabled=1 WHERE jobs.status='delivered' AND jobs.updated_at<=? AND NOT EXISTS (SELECT 1 FROM member_notifications existing WHERE existing.recipient_membership_id=jobs.player_membership_id AND existing.entity_type='stringing_reminder' AND existing.entity_id=jobs.id AND existing.created_at>?)`).bind(now.toISOString(),cutoff.toISOString(),cutoff.toISOString()).run();}

async function deliverPush(env:Bindings,now:Date){if(!env.VAPID_PUBLIC_KEY||!env.VAPID_PRIVATE_KEY||!env.VAPID_SUBJECT)return;const rows=await env.DB.prepare(`SELECT n.id,n.title,n.body,n.entity_type,n.entity_id,m.user_id,s.id AS subscription_id,s.endpoint,s.p256dh,s.auth FROM member_notifications n JOIN club_memberships m ON m.id=n.recipient_membership_id JOIN push_subscriptions s ON s.user_id=m.user_id AND s.enabled=1 LEFT JOIN notification_preferences preferences ON preferences.user_id=m.user_id LEFT JOIN notification_deliveries deliveries ON deliveries.notification_id=n.id AND deliveries.channel='push' WHERE n.created_at>=datetime(?,'-7 days') AND COALESCE(preferences.push_enabled,1)=1 AND (deliveries.id IS NULL OR (deliveries.status='failed' AND deliveries.attempts<4 AND deliveries.next_attempt_at<=?)) ORDER BY n.created_at LIMIT 100`).bind(now.toISOString(),now.toISOString()).all<any>();await Promise.all((rows.results||[]).map(async(row)=>{const deliveryId=crypto.randomUUID();try{const payload=await buildPushPayload({data:JSON.stringify({title:row.title,body:row.body,url:"/",notificationId:row.id,entityType:row.entity_type,entityId:row.entity_id}),options:{ttl:86400,urgency:"high"}},{endpoint:row.endpoint,expirationTime:null,keys:{p256dh:row.p256dh,auth:row.auth}},{subject:env.VAPID_SUBJECT!,publicKey:env.VAPID_PUBLIC_KEY!,privateKey:env.VAPID_PRIVATE_KEY!});const bytes=new Uint8Array(payload.body);const response=await fetch(row.endpoint,{...payload,body:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer});if(response.status===404||response.status===410){await env.DB.prepare(`UPDATE push_subscriptions SET enabled=0,failure_count=failure_count+1,updated_at=? WHERE id=?`).bind(now.toISOString(),row.subscription_id).run();}if(!response.ok)throw new Error(`Push endpoint returned ${response.status}`);await env.DB.prepare(`INSERT INTO notification_deliveries (id,notification_id,user_id,channel,status,attempts,created_at,updated_at) VALUES (?,?,?,'push','sent',1,?,?) ON CONFLICT(notification_id,channel) DO UPDATE SET status='sent',attempts=notification_deliveries.attempts+1,last_error=NULL,updated_at=excluded.updated_at`).bind(deliveryId,row.id,row.user_id,now.toISOString(),now.toISOString()).run();}catch(error){const retry=new Date(now.getTime()+15*60000).toISOString();await env.DB.prepare(`INSERT INTO notification_deliveries (id,notification_id,user_id,channel,status,attempts,last_error,next_attempt_at,created_at,updated_at) VALUES (?,?,?,'push','failed',1,?,?,?,?) ON CONFLICT(notification_id,channel) DO UPDATE SET status='failed',attempts=notification_deliveries.attempts+1,last_error=excluded.last_error,next_attempt_at=excluded.next_attempt_at,updated_at=excluded.updated_at`).bind(deliveryId,row.id,row.user_id,String(error).slice(0,500),retry,now.toISOString(),now.toISOString()).run();}}));}

async function processPrivacyRetention(env:Bindings,now:Date){const retention=new Date(now);retention.setUTCDate(retention.getUTCDate()-90);await env.DB.prepare(`DELETE FROM auth_login_attempts WHERE updated_at<?`).bind(retention.toISOString()).run();await env.DB.prepare(`UPDATE auth_sessions SET revoked_at=COALESCE(revoked_at,?) WHERE expires_at<?`).bind(now.toISOString(),now.toISOString()).run();}

export async function runScheduledWork(env:Bindings,scheduledTime=Date.now()){const now=new Date(scheduledTime);await createAttendanceReminders(env,now);await createStringingReminders(env,now);await deliverPush(env,now);await processPrivacyRetention(env,now);}
